.TH n00bhttpd 8 "21 Dec 2015" "version 1.0" "n00bhttpd"
.SH NAME
n00bhttpd - A minimal web server

.SH SYNOPSIS
.B [port] [index page]

.SH DESCRIPTION
.B n00bhttpd 
is a minimal embedded web server. 
.B WARNING: 
It might have some bugs and may not work as expected.

.SH AUTHOR
Written by Fakhri Zulkifli
